<p style="float: left; width: 100%; padding: 10px 0px;">
    <a href="news/list-all">&laquo; Voltar</a>
</p>   
<div style="float: left;">
    <form name="formNews" method="post" onsubmit="return requiredFormNews();" action="news/<?php echo $data['action']; ?>">
        <table border="1" width="100%">
            <tr>
                <td>Titulo : </td>
                <td>
                    <input type="hidden" name="id" value="<?php echo $data['id']; ?>" />
                    <input type="text" name="title" value="<?php echo $data['title']; ?>" />
                </td>
            </tr>
            <tr>
                <td>Descri&ccedil;&atilde;o : </td>
                <td>
                    <textarea name="description" cols="50" rows="5"><?php echo $data['description']; ?></textarea>
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Salvar" /></td>
            </tr>
        </table>
    </form>
</div>
<script type="text/javascript">
<?php if ($message): ?>
    alert('<?php echo $message; ?>');
<?php endif; ?>
</script>