<p style="float: left; width: 100%; padding: 10px 0px;">
    <a href="news/list-all">&laquo; Voltar</a>
</p>   
<div style="float: left;">
    <form name="formNewsImage" method="post" onsubmit="return requiredFormNewsImage();" action="news/edit-image" enctype="multipart/form-data">
        <table border="1" width="100%">
            <tr>
                <td>Selecione uma imagem : </td>
                <td>
                    <input type="hidden" name="id" value="<?php echo $id; ?>" />
                    <input type="file" name="image" />
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Salvar" /></td>
            </tr>
        </table>
    </form>
</div>
<script type="text/javascript">
<?php if ($message): ?>
        alert('<?php echo $message; ?>');
<?php endif; ?>
</script>